### ISSUE TITLE
Running these images outside of EC2

### ISSUE THREAD

**Issue by srirajan** [lambda-linux/baseimage-amzn#1]
Is the intention of this project to provide AWS Linux Docker images for running locally on a workstation? Typically with Docker that is the use-case. You want developers to run them on their workstations before pushing them to ECS.  I am able to create an image and then download it locally but things like yum don't work in that model. Maybe that is out of scope of what you are trying to do.

Thanks
Sri

**Comment by rajivr** [comment]
We are aware of this use-case. 

_Only_ Amazon can make Amazon Linux RPM packages _publicly_ available outside of AWS. Not us!

We have an FAQ entry for this [here](https://lambda-linux.io/faqs/#!/baseimage-amzn-questions). Please see the question - _Why can't I download baseimage-amzn Docker Images from outside EC2?_

Thank you for using baseimage-amzn.

**Comment by srirajan** [comment]
Thanks for the quick update.  Sorry for missing the FAQ section on that page.  I was thinking of ways around this and an EC2 instance acting as a yum proxy could do the trick.

**Comment by rajivr** [comment]
@srirajan baseimage-amzn is now available on Docker Hub. Please see https://lambda-linux.io/blog/2016/11/03/baseimage-amzn-now-available-on-docker-hub/

**Comment by srirajan** [comment]
Saw that in the AWS announcement. Thanks
