### ISSUE TITLE
Unable to download image 

### ISSUE THREAD

**Issue by monstrocious** [lambda-linux/baseimage-amzn#2]
Getting an Error when attempting to download this image,

Running this command:

docker import https://s3-us-east-1.amazonaws.com/baseimage-amzn-us-east-1/baseimage-amzn-2016.03-003.tar.xz baseimage-amzn:2016.03-003

Response:

Downloading from https://s3-us-east-1.amazonaws.com/baseimage-amzn-us-east-1/baseimage-amzn-2016.03-003.tar.xz
Get https://s3-us-east-1.amazonaws.com/baseimage-amzn-us-east-1/baseimage-amzn-2016.03-003.tar.xz: dial tcp: lookup s3-us-east-1.amazonaws.com: no such host

Please let me know If I'm missing anything, Thanks !

**Comment by rajivr** [comment]
Hi @monstrocious,

`docker import` command on our homepage is AWS region specific. If your Amazon Linux instance is located in US East (N. Virginia) (us-east-1) region, the above command should work.

If you are using a different AWS region, please select your AWS region in the dropdown menu.

Please let us know if you have additional questions.

Thank you for using baseimage-amzn.

Best,
Rajiv

**Comment by rajivr** [comment]
Hi @monstrocious,

Closing this issue. Please re-open if this is still a problem for you.

Thank you for using baseimage-amzn.

Best,
Rajiv
