### ISSUE TITLE
Upstart

### ISSUE THREAD

**Issue by jbussdieker** [lambda-linux/baseimage-amzn#3]
I've been test this image and really like what you've done! I'm running into one problem that I can't seem to figure out related to upstart.

````
$ sudo initctl status foo
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
````

Is this a known limitation?

**Comment by rajivr** [comment]
We do not use upstart in baseimage-amzn. For service supervision we use [runit](http://smarden.org/runit/). It is fairly straightforward to convert upstart conf files to runit service run files. 

If you are new to runit, we recommend checking out these two links - [Use runit!](http://www.mikeperham.com/2014/07/07/use-runit/) and [runit-quickstart](http://kchard.github.io/runit-quickstart/)

Please let us know if you have any further questions.

Thank you for using baseimage-amzn.
